on:
  pull_request:
  push:
    branches: [main]

jobs:
  flake_checks:
    name: Run Nix Flake Checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Run nix flake checks
        # Run these serially (--max-jobs 1) to avoid them competing with each.
        run: nix flake check --all-systems --max-jobs 1 -L
  nix_format:
    name: Check Formatting
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Run nix-fmt
        run: nix fmt **/*.nix -- --check
